### PR TITLE
#846: adds tests for migration strategy `create`

### PR DESCRIPTION
**Pull request by dmarcelino**
Adds tests for PR balderdashy/waterline#853 (issue balderdashy/waterline#846).

### CODE REVIEW

**Comment by devinivy** [comment]
Is this waiting on anything?

**Comment by dmarcelino** [comment]
Finally! :smiley: 

Thanks folks.

**Comment by devinivy** [comment]
Haha, yes this is good news!  Hi @dmarcelino, hope you're well!! :smile: :+1:

**Comment by dmarcelino** [comment]
All is well, cheers!

**Pull request merged**
