### PR TITLE
Fix official adapters integration tests by ignoring redis

### PR DESCRIPTION
**Pull request by dmarcelino**
sails-redis has too many broken tests hence it's not expected they will be fully fixed soon. This PR adds a `returnZeroOnError` flag option that will be enabled for sails-redis only allowing us to ignore its result and prevent it from failing the whole build. Note that sails-redis build result will still be available at the end of build log so it's possible to monitor its progress!

### CODE REVIEW

**Comment by devinivy** [comment]
Pending CI, this looks great to me :)

**Comment by dmarcelino** [comment]
Fingers crossed! travis is so slow today because of them rolling back their April release... :angry:

**Comment by dmarcelino** [comment]
It's green! :green_apple: , :green_book: , :green_heart: , :recycle: green!!! For the first time :smiley: 

:confetti_ball: :confetti_ball:  :confetti_ball:

**Comment by devinivy** [comment]
Gorgeous!

**Pull request merged**
