### PR TITLE
Adds support for mocha chainable methods 

### PR DESCRIPTION
**Pull request by dmarcelino**
In "sails-adapter-boilerplate" [index.js](https://github.com/balderdashy/sails-adapter-boilerplate/blob/master/index.js#L17-L18) it's suggested:

>  If you don't need / can't get to every method, just implement what you have time for.

That's great but the integration tests will probably break which is very annoying (and the sentiment is also shared by other users in balderdashy/sails-adapter-boilerplate#8 and #33).

This change adds support for mocha [chainable methods](https://github.com/mochajs/mocha/wiki/Using-mocha-programmatically#set-options) such as `invert()`. To use this, the adapter developer only needs to add a `mochaChainableMethods` object with keys matching the chainable methods and the values matching the arguments, example:
``` javascript
    // Mocha options
    // reference: https://github.com/mochajs/mocha/wiki/Using-mocha-programmatically
    mocha: {
      reporter: 'spec',
      grep: /escape attribute names to prevent SQL injection|findOrCreateEach/
    },

    mochaChainableMethods: {
      invert: true,
    }
```
With this errors regarding SQL injection attacks and findOrCreateEach will be ignored.

### CODE REVIEW

**Comment by dmarcelino** [comment]
@tjwebb, @devinivy, please take a look at this change. It's fairly benign and it will add flexibility for those creating adapters.

**Comment by devinivy** [comment]
Seems okay to me, as long as this wont be used for evil!  Is there any possibility we'd like to identify some tests that _must_ pass?

**Comment by dmarcelino** [comment]
That's a fair question @devinivy. According to [sails-adapter-boilerplate index.js#L102](https://github.com/balderdashy/sails-adapter-boilerplate/blob/master/index.js#L102):
> [registerCollection] is the only required method.

Given you can't do much without registering a connection I would said any mix of tests always cover that requirement. My expectation is that official adapters should always pass all tests and that community adapters may opt-out certain features. As it stands now, authors of adapters that don't implement the full spec are discouraged from using the adapter-tests.

**Comment by dmarcelino** [comment]
Thanks @devinivy!

**Comment by devinivy** [comment]
:+1:

**Pull request merged**
