### PR TITLE
Add cross adapter tests: final proposal

### PR DESCRIPTION
**Pull request by dmarcelino**
Given @particlebanana did a great job at fixing the integrator this PR is an additional iteration over PR #57 to make it more robust, backwards compatible and more consistent (crossAdapter is no longer in the interfaces folder).

After these changes, the cross-adapter tests will only run for adapters with `features` in its package.json like:
```javascript
  "waterlineAdapter": {
    //...
    "features": [
      "cross-adapter"
    ]
  }
```
This way it won't break tests for adapters that don't fully support this yet (e.g. sails-orientdb).

Another advantage of this setup is the ability to add additional feature sets of tests in `/features/` which are configurable via package.json.

Note: after this is merged we'll need to change sails-postgresql, sails-memory, sails-disk, sails-mongo and sails-mysql package.json to include the "cross-adapter" feature.

Original proposal text:
> Adds failing tests for balderdashy/waterline#925 and related issues.
> 
> This change makes use of the existing `Associations` tests by re-running them while using sails-memory in some of the associations. By doing this we get a comprehensive suite of cross adapter tests that cover the same ground as the existing Associations tests.
> 
> In this PR the cross adapter tests never exit with non-zero to avoid breaking the build while we work on balderdashy/waterline#925. It's still possible to see their results in the end of the build:
> ```
> | adapter          | version | result | failed | total | wl-sequel |
> |------------------|---------|--------|--------|-------|-----------|
> | sails-postgresql | 0ad94e5 | passed |     13 |   276 |     0.3.1 |
> | sails-memory     | 7cf3600 | passed |     25 |   273 |           |
> | sails-disk       | 5210c18 | passed |     26 |   272 |           |
> | sails-mongo      | ae251dc | passed |     11 |   251 |           |
> | sails-mysql      | d289f11 | passed |      1 |   231 |     0.3.1 |
> | sails-redis      | 6eb8f92 | failed |     72 |   272 |           |
> ```
> Currently there too many cross adapter tests failing and MySQL did not even run them (I'll have to > investigate). PR balderdashy/waterline#848 makes 8 additional tests pass!
https://travis-ci.org/balderdashy/waterline-adapter-tests/jobs/60511926#L4695

> **Roadmap**
> 1. Add cross adapter tests that never return non-zero (this PR);
> 2. Fix balderdashy/waterline#925;
> 3. Make crossAdapter tests only run if configured by the adapter;
> 4. Make crossAdapter tests exit with non-zero if any tests fails.

cc: @tjwebb, @devinivy

### CODE REVIEW

**Comment by devinivy** [comment]
In what way do cross-adapter features rely on adapter functionality?  I thought this all came down to the integrator in waterline, but it seems I'm misunderstanding.  For example, what does sails-orientbd need to do to become cross-adapter compatible?

**Comment by dmarcelino** [comment]
Hi @devinivy, so without getting too deep on OrientDB, OrientDB has 3 important classes (its equivalent of tables): `Document`, `Vertex and `Edge` (the last 2 extend the former). In graphDB mode, associations are made using edges that connect vertexes. This works perfectly outside a cross-adapter scenario but currently it breaks on cross-adapter mode. We will need to change sails-orientdb to detect if a given association is cross-adapter and if so use a `Document` (instead of `Edge`) as join table to hold the other side's FKey.

Currently, an adapter can implement `Semantic` and `Queryable`, which would mean it supports `Associations`, and still have have `Associations` turned off in the `package.json`. As you mention, current adapter philosophy is a bit like *you can implement what you want*, and my proposal abides to that. If we are changing the community adapter philosophy then I agree with you. There will be a tradeoff however, as the higher the demand is the more people will feel demotivated and may not want to use the waterline-adapter-tests as it will become harder to get them to pass.

**Comment by devinivy** [comment]
Okay– sounds good.  We should think about this more, and maybe at least make sure the features/interfaces are transparently shown in the adapter readmes.  Perhaps WL needs adapter badges :P.  This PR looks good.

**Comment by dmarcelino** [comment]
> Perhaps WL needs adapter badges :P

That actually sounds like a good idea! :smiley:

**Comment by dmarcelino** [comment]
BTW, another advantage of having optional `features` is that we can add tests for db constraints like `unique` (#63) and `autoincrement`.

The badges part is actually not that difficult :wink: :

[interfaces](https://github.com/balderdashy/sails-docs/blob/master/contributing/adapter-specification.md)
[features](https://github.com/balderdashy/sails-docs/blob/master/contributing/adapter-specification.md)

```
[![interfaces](https://img.shields.io/badge/interface-associations-brightgreen.svg)](https://github.com/balderdashy/sails-docs/blob/master/contributing/adapter-specification.md)
[![features](https://img.shields.io/badge/feature-cross--adapter-yellow.svg)](https://github.com/balderdashy/sails-docs/blob/master/contributing/adapter-specification.md)
```

**Comment by devinivy** [comment]
@dmarcelino what tasks need to be done to get this merged?

**Comment by dmarcelino** [comment]
> @dmarcelino what tasks need to be done to get this merged?

Pushing the big green "Merge pull request button"? :stuck_out_tongue: 

Sorry, couldn't resist myself :blush: ... From waterline-adapter-tests perspective this is done and complete. It's *mergeable* as it is without breaking any tests because no adapter has cross-adapter feature enabled. In my opinion we should do this in the following order:

- [ ] 1. Merge PR balderdashy/waterline#984
- [ ] 2. Enable cross-adapter feature in all official adapters ( `"waterlineAdapter": { "features": ["cross-adapter"] }` );
- [ ] 3. re-run travis build and make sure all tests are passing
- [ ] 4. merge this PR.

All this provided we choose this PR over @particlebanana's #62.

**Comment by particlebanana** [comment]
Looks like an issue with sails-mysql on the cross-adapter tests. Looking into it.

**Comment by particlebanana** [comment]
Fixed mysql with https://github.com/balderdashy/sails-mysql/commit/4145e0793ea8abebc46c95f54000858b56e82175 so lets see what else errors.

**Pull request merged**
