### PR TITLE
Integration Test improvements

### PR DESCRIPTION
**Pull request by dmarcelino**
Continues the work done in #36.

* Table now shows the number of failed tests, example below;
* Full javascript solution, no more **runner.sh**;
* Added sails-redis to the tests;
* Adds README.md;
* Example build: https://travis-ci.org/balderdashy/waterline-adapter-tests/jobs/56210085#L1351

| adapter          | version | status  | failed | total | wl-sequel |
|------------------|---------|---------|--------|-------|-----------|
| sails-postgresql | fbbe1c6 | success |      0 |   225 | 0.1.1     |
| sails-memory     | 7cf3600 | failed  |      1 |   202 |           |
| sails-disk       | 7e09b27 | failed  |      1 |   205 |           |
| sails-mongo      | 414d748 | failed  |      6 |   201 |           |
| sails-mysql      | afb39ed | failed  |      4 |   226 | 0.1.1     |
| sails-redis      | 6eb8f92 | failed  |     40 |   204 |           |

### CODE REVIEW

**Comment by dmarcelino** [comment]
@tjwebb, @devinivy, @particlebanana, please take a look at this. TL;DR: removes bash script and replaces it with javascript, shows number of failed tests, shows the versions of the components tested, adds sails-redis and added a README.md.

**Comment by devinivy** [comment]
I don't currently have time to test this out, but the code itself looks good to me.  Is it behaving as expected, @dmarcelino?

**Comment by dmarcelino** [comment]
Yeap, you can see the results for yourself here: https://travis-ci.org/balderdashy/waterline-adapter-tests/jobs/56210085#L1360.

And when we sort out the SQL interface, sails-memory and sails-disk will also turn green.

**Comment by tjwebb** [comment]
Woohoo! :+1:

**Comment by dmarcelino** [comment]
Thanks @devinivy, @tjwebb!

**Pull request merged**
