### PR TITLE
fixes autoIncrement test

### LINKED ISSUE #85: autoIncrement test sorts results by name, but tests the ordering using id
https://travis-ci.org/waterlinejs/postgresql-adapter/builds/75205050#L1026

This test sorts on `name`, but tests the resulting order based on `id`. The test wrongly assumes that records are inserted serially rather than in parallel. Sort order of results should not be assumed in this way.

### PR DESCRIPTION
**Pull request by tjwebb**
- resolves #85

### CODE REVIEW

**Comment by dmarcelino** [comment]
+1

**Comment by devinivy** [comment]
Looks good!

**Comment by tjwebb** [comment]
@particlebanana can you publish to npm when you get a chance? Thanks

**Comment by particlebanana** [comment]
@tjwebb done

**Pull request merged**
