### PR TITLE
Remove insertion order dependency

### PR DESCRIPTION
**Pull request by khalilTN**
Insertion order may not be respected by the DBMS, that's why some tests which depend on insertion order to be the same as the order of .create() calls may fail. Adding sorts by numeric attributes fulfilled the task (In 3 cases, addition of new numeric attributes to models to ensure sort).

### CODE REVIEW

**Comment by dmarcelino** [comment]
For references, this issue fixes #26.

@khalilTN, @atiertant, it's not possible to merge this PR. @khalilTN, can you merge the latest version of master into your branch and fix any conflicts?

**Comment by atiertant** [comment]
@dmarcelino all is ok now ;)

**Comment by dmarcelino** [comment]
Good stuff, looks good! :white_check_mark:

@devinivy, are you OK with these changes?

**Comment by devinivy** [comment]
Yeah, I like it!

**Comment by dmarcelino** [comment]
Thanks @khalilTN, @atiertant!

**Comment by khalilTN** [comment]
@dmarcelino u r welcome !

**Pull request merged**
