### PR TITLE
Add cross adapter tests

### PR DESCRIPTION
**Pull request by dmarcelino**
Adds failing tests for balderdashy/waterline#925 and related issues.

This change makes use of the existing `Associations` tests by re-running them while using sails-memory in some of the associations. By doing this we get a comprehensive suite of cross adapter tests that cover the same ground as the existing Associations tests.

In this PR the cross adapter tests never exit with non-zero to avoid breaking the build while we work on balderdashy/waterline#925. It's still possible to see their results in the end of the build:
```
| adapter          | version | result | failed | total | wl-sequel |
|------------------|---------|--------|--------|-------|-----------|
| sails-postgresql | 0ad94e5 | passed |     13 |   276 |     0.3.1 |
| sails-memory     | 7cf3600 | passed |     25 |   273 |           |
| sails-disk       | 5210c18 | passed |     26 |   272 |           |
| sails-mongo      | ae251dc | passed |     11 |   251 |           |
| sails-mysql      | d289f11 | passed |      1 |   231 |     0.3.1 |
| sails-redis      | 6eb8f92 | failed |     72 |   272 |           |
```
Currently there too many cross adapter tests failing and MySQL did not even run them (I'll have to investigate). PR balderdashy/waterline#848 makes 8 additional tests pass!
https://travis-ci.org/balderdashy/waterline-adapter-tests/jobs/60511926#L4695

**Roadmap**
1. Add cross adapter tests that never return non-zero (this PR);
2. Fix balderdashy/waterline#925;
3. Make crossAdapter tests only run if configured by the adapter;
4. Make crossAdapter tests exit with non-zero if any tests fails.

### CODE REVIEW

**Comment by devinivy** [comment]
I suppose the only thing to bring-up is semantical– `crossAdapter` isn't an interface, and it would generally be waterline's fault (rather than an adapter's fault) if cross-adapter querying doesn't work.  Hmm!  Looks great though– wonderful that you were able to leverage existing tests.

**Comment by dmarcelino** [comment]
That's a good point... though I can't think of any other good way for an adapter to run them or not. Unless they are configured via runner.js (that's a possibility).

BTW even though an adapter doesn't have to implement anything it still can break cross adapter tests by its own fault. Example: I've noticed that in sails-orientdb because the edge of a graph (the "join table") can't point to a fkey in another database I'm getting more failed tests with the cross adapter tests than the official adapters.

**Comment by dmarcelino** [comment]
I was just thinking... maybe instead of having these tests in `interfaces/crossAdapter` we should move them to a new folder like `features/crossAdapter`. That would give us a place to put other non-interface / optional tests like, for example, `features/schemaless` (issues like balderdashy/waterline#366 could use it). These would also be enabled through the package.json like interfaces is currently. What do you think @devinivy?

**Comment by dmarcelino** [comment]
@devinivy, regarding my last suggestions I've added PR #64, let me know what you think.

**Comment by dmarcelino** [comment]
Closing this for now since PR #64 is more mature than this one.

**Pull request closed without merging**
